apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudethix-nginx-paresh
  namespace: cloudethix-paresh
  labels: 
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata: 
      labels:
        app: nginx
    spec:
      containers:
      - name: cloudethix-nginx-paresh
        image: paresh28/cloudethix-nginix-paresh:v1
        ports:
        - containerPort: 80
